// 카테고리 데이터
export const CATEGORIES = [
  {
    category_id: 1,
    name: "일상",
    icon: "notebook-outline",
    color: "#69BAFF",
  },
  {
    category_id: 2,
    name: "소비",
    icon: "piggy-bank",
    color: "#FFD700",
  },
  {
    category_id: 3,
    name: "할일",
    icon: "clipboard-check-outline",
    color: "#4CAF50",
  },
  {
    category_id: 4,
    name: "건강",
    icon: "heart-pulse",
    color: "#FF5656",
  },
  {
    category_id: 5,
    name: "기타",
    icon: "dots-horizontal-circle-outline",
    color: "#333333",
  },
];

// 카테고리 아이콘 매핑 (RecordList에서 사용)
export const CATEGORY_ICONS = {
  일상: {
    name: "notebook-outline",
    color: "#69BAFF",
  },
  소비: {
    name: "piggy-bank",
    color: "#FFD700",
  },
  할일: {
    name: "clipboard-check-outline",
    color: "#4CAF50",
  },
  건강: {
    name: "heart-pulse",
    color: "#FF5656",
  },
  기타: {
    name: "dots-horizontal-circle-outline",
    color: "#333333",
  },
};

// 레코드 더미데이터
export const RECORDS = [
  {
    record_id: 1,
    category_id: 1,
    record_date: "2024-03-20",
    record_time: "09:30",
    content: "오늘의 일상 기록입니다.",
  },
  {
    record_id: 2,
    category_id: 2,
    record_date: "2024-03-20",
    record_time: "12:15",
    content: "점심 식사 비용 8,000원",
  },
  {
    record_id: 3,
    category_id: 3,
    record_date: "2024-03-19",
    record_time: "15:45",
    content: "프로젝트 마감일까지 3일 남음",
  },
  {
    record_id: 4,
    category_id: 4,
    record_date: "2024-03-19",
    record_time: "18:20",
    content: "오늘 30분 운동 완료",
  },
  {
    record_id: 5,
    category_id: 5,
    record_date: "2024-03-18",
    record_time: "10:00",
    content: "주간 회의 일정 확인",
  },
  {
    record_id: 6,
    category_id: 1,
    record_date: "2024-03-18",
    record_time: "14:30",
    content: "새로운 아이디어 메모",
  },
  {
    record_id: 7,
    category_id: 2,
    record_date: "2024-03-17",
    record_time: "11:20",
    content: "장보기 35,000원",
  },
  {
    record_id: 8,
    category_id: 3,
    record_date: "2024-03-17",
    record_time: "16:00",
    content: "주말 과제 완료",
  },
  {
    record_id: 9,
    category_id: 4,
    record_date: "2024-03-16",
    record_time: "07:30",
    content: "아침 조깅 5km",
  },
  {
    record_id: 10,
    category_id: 5,
    record_date: "2024-03-16",
    record_time: "20:00",
    content: "친구와 영화 관람",
  },

  // 4월 7일
  {
    record_id: 11,
    record_date: "2025-04-07",
    record_time: "09:30",
    content: "아침 운동 완료! 러닝 30분",
    record_status: "RECORD_REGISTERED",
    category_id: 4,
  },
  {
    record_id: 12,
    record_date: "2025-04-07",
    record_time: "12:15",
    content: "점심 식사 - 샐러드 12,000원",
    record_status: "RECORD_REGISTERED",
    category_id: 2,
  },
  {
    record_id: 13,
    record_date: "2025-04-07",
    record_time: "15:45",
    content: "업무 회의 진행",
    record_status: "RECORD_REGISTERED",
    category_id: 3,
  },
  {
    record_id: 14,
    record_date: "2025-04-07",
    record_time: "18:30",
    content: "퇴근 후 동료와 저녁 식사",
    record_status: "RECORD_REGISTERED",
    category_id: 1,
  },

  // 4월 8일
  {
    record_id: 15,
    record_date: "2025-04-08",
    record_time: "08:45",
    content: "아침 명상 20분",
    record_status: "RECORD_REGISTERED",
    category_id: 4,
  },
  {
    record_id: 16,
    record_date: "2025-04-08",
    record_time: "11:30",
    content: "프로젝트 기획안 작성",
    record_status: "RECORD_REGISTERED",
    category_id: 3,
  },
  {
    record_id: 17,
    record_date: "2025-04-08",
    record_time: "14:20",
    content: "커피 브레이크 - 아메리카노 4,500원",
    record_status: "RECORD_REGISTERED",
    category_id: 2,
  },

  // 4월 9일
  {
    record_id: 18,
    record_date: "2025-04-09",
    record_time: "10:00",
    content: "도서관에서 책 대여",
    record_status: "RECORD_REGISTERED",
    category_id: 1,
  },
  {
    record_id: 19,
    record_date: "2025-04-09",
    record_time: "13:15",
    content: "점심 식사 - 김치찌개 9,000원",
    record_status: "RECORD_REGISTERED",
    category_id: 2,
  },
  {
    record_id: 20,
    record_date: "2025-04-09",
    record_time: "16:45",
    content: "주간 보고서 작성",
    record_status: "RECORD_REGISTERED",
    category_id: 3,
  },
  {
    record_id: 21,
    record_date: "2025-04-09",
    record_time: "19:30",
    content: "저녁 요가 수업",
    record_status: "RECORD_REGISTERED",
    category_id: 4,
  },
  {
    record_id: 22,
    record_date: "2025-04-09",
    record_time: "22:00",
    content: "일기 쓰기",
    record_status: "RECORD_REGISTERED",
    category_id: 1,
  },

  // 4월 10일
  {
    record_id: 23,
    record_date: "2025-04-10",
    record_time: "09:15",
    content: "아침 스트레칭",
    record_status: "RECORD_REGISTERED",
    category_id: 4,
  },
  {
    record_id: 24,
    record_date: "2025-04-10",
    record_time: "12:30",
    content: "동료와 점심 미팅",
    record_status: "RECORD_REGISTERED",
    category_id: 3,
  },
  {
    record_id: 25,
    record_date: "2025-04-10",
    record_time: "15:00",
    content: "새 노트북 구매 - 1,500,000원",
    record_status: "RECORD_REGISTERED",
    category_id: 2,
  },

  // 4월 11일
  {
    record_id: 26,
    record_date: "2025-04-11",
    record_time: "10:30",
    content: "병원 정기 검진",
    record_status: "RECORD_REGISTERED",
    category_id: 4,
  },
  {
    record_id: 27,
    record_date: "2025-04-11",
    record_time: "13:45",
    content: "프로젝트 미팅",
    record_status: "RECORD_REGISTERED",
    category_id: 3,
  },
  {
    record_id: 28,
    record_date: "2025-04-11",
    record_time: "16:20",
    content: "카페에서 독서",
    record_status: "RECORD_REGISTERED",
    category_id: 1,
  },
  {
    record_id: 29,
    record_date: "2025-04-11",
    record_time: "19:00",
    content: "저녁 식사 - 파스타 18,000원",
    record_status: "RECORD_REGISTERED",
    category_id: 2,
  },

  // 4월 12일
  {
    record_id: 30,
    record_date: "2025-04-12",
    record_time: "08:00",
    content: "주말 조깅",
    record_status: "RECORD_REGISTERED",
    category_id: 4,
  },
  {
    record_id: 31,
    record_date: "2025-04-12",
    record_time: "11:00",
    content: "마트 장보기 - 65,000원",
    record_status: "RECORD_REGISTERED",
    category_id: 2,
  },
  {
    record_id: 32,
    record_date: "2025-04-12",
    record_time: "14:30",
    content: "친구와 카페",
    record_status: "RECORD_REGISTERED",
    category_id: 1,
  },
  {
    record_id: 33,
    record_date: "2025-04-12",
    record_time: "17:00",
    content: "주간 할일 정리",
    record_status: "RECORD_REGISTERED",
    category_id: 3,
  },
  {
    record_id: 34,
    record_date: "2025-04-12",
    record_time: "20:15",
    content: "취미 그림 그리기",
    record_status: "RECORD_REGISTERED",
    category_id: 5,
  },

  // 4월 13일
  {
    record_id: 35,
    record_date: "2025-04-13",
    record_time: "09:45",
    content: "아침 요가",
    record_status: "RECORD_REGISTERED",
    category_id: 4,
  },
  {
    record_id: 36,
    record_date: "2025-04-13",
    record_time: "12:00",
    content: "일요일 브런치 - 25,000원",
    record_status: "RECORD_REGISTERED",
    category_id: 2,
  },
  {
    record_id: 37,
    record_date: "2025-04-13",
    record_time: "15:30",
    content: "다음 주 일정 계획",
    record_status: "RECORD_REGISTERED",
    category_id: 3,
  },
  {
    record_id: 38,
    record_date: "2025-04-13",
    record_time: "18:00",
    content: "가족 저녁 식사",
    record_status: "RECORD_REGISTERED",
    category_id: 1,
  },

  // 4월 14일
  {
    record_id: 39,
    record_date: "2025-04-14",
    record_time: "08:30",
    content: "아침 미팅 준비",
    record_status: "RECORD_REGISTERED",
    category_id: 3,
  },
  {
    record_id: 40,
    record_date: "2025-04-14",
    record_time: "11:45",
    content: "점심 도시락 - 8,000원",
    record_status: "RECORD_REGISTERED",
    category_id: 2,
  },
  {
    record_id: 31,
    record_date: "2025-04-14",
    record_time: "14:00",
    content: "건강검진 예약",
    record_status: "RECORD_REGISTERED",
    category_id: 4,
  },
  {
    record_id: 32,
    record_date: "2025-04-14",
    record_time: "17:30",
    content: "퇴근 후 산책",
    record_status: "RECORD_REGISTERED",
    category_id: 1,
  },
  {
    record_id: 33,
    record_date: "2025-04-14",
    record_time: "20:00",
    content: "취미 피아노 연습",
    record_status: "RECORD_REGISTERED",
    category_id: 5,
  },
];
