name: Discord Webhook Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        run: |
          curl -X POST "$DISCORD_WEBHOOK" \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"📢 New push to main by ${{ github.actor }}\"}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
